Update requirements.txt
Resolving conflict with different versions of python-dotenv:

ERROR: Cannot install -python-dotenv==1.0.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested python-dotenv==1.0.1
    crewai 0.22.5 depends on python-dotenv==1.0.0